---
title: "a2"
format: html
editor: visual
---

This guide will demonstrate how to use git ..\
\*\*\* INTRO REQUIRED \*\*\*

1.  Create an RStudio project. In this folder, create a simple qmd file called `example.qmd` that can be knitted into a HTML file. Show the result of the knitted file.

-   First, open RStudio.

-   Then navigate to the File section, and select "New Project" as shown below\
    (insert ss).

-   Select "New Directory", and then select "New Project".

-   Set your desired directory name and choose where you want the project to be stored, as shown below, then click on "Create Project"\
    (insert ss)\

-   Navigate to the File section like in fig1, in the new project we just created, and click on "New File", and select "Quarto Document" to create a .qmd file.

-   Upon creating the Qmd file, select the "Render" button as shown in the figure below. Rendering the qmd file will require you to save it first.\
    (insert fig)

-   The rendered (or knitted) html will open in the web browser as shown\
    (insert fig)

2.  From the command line interface, initialise this folder as a git repository and push it to a GitHub repository.

-   RStudio has a section called "Terminal" that is a Command Line Interface (CLI), so we will be using it to perform all CLI based tasks.

-   , we will use the CLI and open the directory for the folder.

-   then use the command `git init` to initialise the folder as a git repository
